watch_stylesheet: true
watch_config: true

bars:
    yasb-bar:
        enabled: true
        screens: ['*']
        class_name: 'yasb-bar'
        alignment:
            position: 'top'
            center: true
        window_flags:
            always_on_top: false
            windows_app_bar: true
        dimensions:
            height: 48
        widgets:
            left:
                [
                    'power_buttons',
                    'komorebi_workspaces',
                    'komorebi_active_layout',
                    'active_window'
                ]
            right:
                [
                    'explorer_button',
                    'cpu_icon',
                    'cpu',
                    'memory_icon',
                    'memory',
                    'wifi',
                    'battery',
                    'clock'
                ]
widgets:
    active_window:
        type: 'yasb.active_window.ActiveWindowWidget'
        options:
            label: '\u276f  {win[title]}'
            label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
            label_no_window: ''
            max_length: 48
            max_length_ellipsis: '...'
            monitor_exclusive: false

    battery:
        type: 'yasb.battery.BatteryWidget'
        options:
            time_remaining_natural: true
            charging_options:
                icon_format: '{charging_icon}{icon}'
            status_icons:
                icon_charging: "\ueeca"
                icon_critical: "\uea34"
                icon_low: "\uea2f"
                icon_medium: "\uea30"
                icon_high: "\uea31"
                icon_full: "\uea32"

    clock:
        type: 'yasb.clock.ClockWidget'
        options:
            label: '{%a %d %b. %H:%M}'
            timezones: ['Europe/Stockholm']
            callbacks:
                on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
                on_right: 'next_timezone'

    cpu:
        type: 'yasb.cpu.CpuWidget'
        options:
            label: '{info[percent][total]}%'
            update_interval: 500
            histogram_num_columns: 10

    memory:
        type: 'yasb.memory.MemoryWidget'
        options:
            label: '{virtual_mem_free}'
            label_alt: '{virtual_mem_percent}%'
            update_interval: 5000
            callbacks:
                on_right: 'exec cmd /c Taskmgr'

    komorebi_workspaces:
        type: 'komorebi.workspaces.WorkspaceWidget'
        options:
            label_offline: ''
            label_workspace_btn: '{name}'
            label_default_name: '{index}'
            label_zero_index: false
            hide_empty_workspaces: false

    komorebi_active_layout:
        type: 'komorebi.active_layout.ActiveLayoutWidget'
        options:
            hide_if_offline: true
            label: '{icon}'
            layout_icons:
                bsp: "[\\\\]"
                columns: '[||]'
                rows: '[==]'
                vertical_stack: '[V]='
                horizontal_stack: '[H]='
                ultrawide_vertical_stack: '||='
                monocle: '[M]'
                maximised: '[X]'
                floating: '><>'
                paused: '[P]'
            callbacks:
                on_left: 'next_layout'
                on_middle: 'toggle_monocle'
                on_right: 'prev_layout'

    wifi:
        type: 'yasb.wifi.WifiWidget'
        options:
            label: '{wifi_icon}'
            label_alt: '{wifi_icon} {wifi_name}'
            update_interval: 5000
            wifi_icons:
                - "\uecfa" # 0% strength (no wifi)
                - "\ueba3" # 1-25% strength
                - "\ueba4" # 26-50% strength
                - "\ueba5" # 51-75% strength
                - "\ueb52" # 76-100% strength.
            callbacks:
                on_middle: 'do_nothing'
                on_right: 'exec cmd.exe /c start ms-settings:network'

    power_buttons:
        type: 'yasb.power_buttons.PowerButtonsWidget'
        options:
            label: "\uecd8"
    # Some custom widgets
    explorer_button:
        type: 'yasb.custom.CustomWidget'
        options:
            label: "\ueaad"
            label_alt: 'Explorer'
            class_name: 'explorer-widget'
            exec_options:
                run_once: true
            callbacks:
                on_left: 'exec explorer.exe'
                on_right: 'toggle_label'

    notifications_button:
        type: 'yasb.custom.CustomWidget'
        options:
            label: "\ue7f4"
            label_alt: 'Notifications'
            class_name: 'notifications-widget'
            exec_options:
                run_once: true
            callbacks:
                on_left: 'exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App'
                on_right: 'toggle_label'

    cpu_icon:
        type: 'yasb.custom.CustomWidget'
        options:
            label: "\uef8e"
            label_alt: "\uf075"
            class_name: 'cpu-icon-widget'

    memory_icon:
        type: 'yasb.custom.CustomWidget'
        options:
            label: "\ueed2"
            label_alt: "\ueed2"
            class_name: 'memory-icon-widget'
