gui:
  sidePanelWidth: 0.25
  scrollHeight: 20
  nerdFontsVersion: "3"
  authorColors:
    "*": magenta
  skipRewordInEditorWarning: true
  theme:
    selectedLineBgColor:
      - black
  border: single
git:
  paging:
    # Requires: https://github.com/Wilfred/difftastic
    externalDiffCommand: difft --color=always --display=inline --syntax-highlight=on --tab-width=2
notARepository: "skip"
