general:
  cursor_follows_focus: true
  window_animations: false

gaps:
  inner_gap: "20px"
  outer_gap: "20px"

focus_borders:
  active:
    enabled: true
    color: '#c4a7e7'

bar:
  height: '30px'
  position: 'top'
  opacity: 1.0
  background: '#191724CC'
  foreground: '#e0def4'
  border_width: '1px'
  border_color: '#413f4a'
  font_family: 'Inter'
  font_size: '13px'
  font_weight: '600'
  padding: '4px 6px'
  margin: '10px'
  offset_x: '20px'
  offset_y: '10px'
  border_radius: '8px'
  components_left:
    - type: "image"
      source: "C:/Users/ADKA01/.config/glazewm/icons/avatar-base.ico"
      margin: '0 4px'
      padding: '0 8px 0 0'
    - type: 'workspaces'
      font_family: 'Symbols Nerd Font'
      font_weight: '400'
      font_size: '18px'
      border_radius: '8px'
      border_width: '1px'
      border_color: '#413f4a'
      margin: '-2px'
      focused_workspace_foreground: '#eb6f92'
      focused_workspace_background: 'transparent'
      displayed_workspace_foreground: '#e0def4'
      displayed_workspace_background: 'transparent'
      default_workspace_foreground: '#e0def4'
      default_workspace_background: 'transparent'
    - type: 'tiling direction'
      font_size: '16px'
      label_horizontal: '⮂'
      label_vertical: '⮁'
      margin: '0 4px'
      padding: '0 8px'
    - type: 'window title'
  components_center:
    - type: "music"
      label_not_playing: ""
      label_paused: "{song_title} - {artist_name}"
      label_playing: "{song_title} - {artist_name}"
      max_title_length: 40
      max_artist_length: 40
  components_right:
    - type: 'binding mode'
      background: '#eb6f92'
      margin: '0 4px 0 0'
      padding: '0 8px'
    - type: "cpu"
      label: "<attr fg='#f6c177' ff='Symbols Nerd Font' fw='400' fs='18'>󰍛 </attr> {percent_usage}%"
      refresh_interval_ms: 1000
      margin: '0 4px 0 0'
      padding: '0 8px'
    - type: "memory"
      label: "<attr fg='#9ccfd8' ff='Symbols Nerd Font' fw='400' fs='18'>󰑭 </attr> {percent_usage}%"
      refresh_interval_ms: 1000
      margin: '0 4px 0 0'
      padding: '0 8px'
    - type: 'weather'
      latitude: 59.334591
      longitude: 18.063240
      label: '{temperature_celsius}°C'
      label_sun: "<attr fg='#f6c177' ff='Symbols Nerd Font' fw='400' fs='20'> </attr> {temperature_celsius}°C"
      label_moon: "<attr fg='#f6c177' ff='Symbols Nerd Font' fw='400' fs='20'> </attr> {temperature_celsius}°C"
      label_cloud_moon: "<attr fg='#f6c177' ff='Symbols Nerd Font' fw='400' fs='20'> </attr> {temperature_celsius}°C"
      label_cloud_sun: "<attr fg='#f6c177' ff='Symbols Nerd Font' fw='400' fs='20'> </attr> {temperature_celsius}°C"
      label_cloud_moon_rain: "<attr fg='#9ccfd8' ff='Symbols Nerd Font' fw='400' fs='20'> </attr> {temperature_celsius}°C"
      label_cloud_sun_rain: "<attr fg='#9ccfd8' ff='Symbols Nerd Font' fw='400' fs='20'> </attr> {temperature_celsius}°C"
      label_cloud_rain: "<attr fg='#9ccfd8' ff='Symbols Nerd Font' fw='400' fs='20'> </attr> {temperature_celsius}°C"
      label_snow_flake: "<attr fg='#e0def4' ff='Symbols Nerd Font' fw='400' fs='20'> </attr> {temperature_celsius}°C"
      label_thunderstorm: "<attr fg='#f6c177' ff='Symbols Nerd Font' fw='400' fs='20'>󰖓 </attr> {temperature_celsius}°C"
      label_cloud: "<attr fg='#e0def4' ff='Symbols Nerd Font' fw='400' fs='20'> </attr> {temperature_celsius}°C"
      margin: '0 4px'
      padding: '0 8px'
    - type: 'battery'
      label_draining: "<attr fg='#f6c177' ff='Symbols Nerd Font' fw='400' fs='16'> </attr> {battery_level}%"
      label_power_saver: "<attr fg='#eb6f92' ff='Symbols Nerd Font' fw='400' fs='16'> </attr> {battery_level}%"
      label_charging: "<attr fg='#31748f' ff='Symbols Nerd Font' fw='400' fs='16'> </attr> {battery_level}%"
      margin: '0 4px'
      padding: '0 8px'
    - type: 'volume'
      label_mute: "<attr ff='Symbols Nerd Font' fw='400' fs='18'>󰝟 </attr>"
      label_low: "<attr ff='Symbols Nerd Font' fw='400' fs='18'>󰖀 </attr> {volume_level}%"
      label_medium: "<attr ff='Symbols Nerd Font' fw='400' fs='18'>󰖀 </attr> {volume_level}%"
      label_high: "<attr ff='Symbols Nerd Font' fw='400' fs='18'>󰕾 </attr> {volume_level}%"
      margin: '0 4px'
      padding: '0 8px'
    - type: 'clock'
      time_formatting: 'ddd dd MMM. HH:mm'
      margin: '0 4px'
      padding: '0 8px'

window_rules:
  - command: 'ignore'
    match_process_name: '/Taskmgr|ScreenClippingHost/'
  - command: 'set floating'
    match_class_name: '#32770'
  - command: 'ignore'
    match_title: '[Pp]icture.in.[Pp]icture'
    match_class_name: 'Chrome_WidgetWin_1|MozillaDialogClass'
  - command: 'move to workspace 1'
    match_process_name: '/firefox|chrome|edge|vivaldi/'
  - command: 'move to workspace 2'
    match_process_name: '/Code|devenv|wezterm-gui/'
  - command: 'move to workspace 3'
    match_process_name: '/ms-teams|olk|Slack/'
  - command: 'move to workspace 4'
    match_process_name: '/Spotify/'
    
workspaces:
  - name: "1"
    display_name: "󰖟"
  - name: "2"
    display_name: "󰅴"
  - name: "3"
    display_name: "󰻞"
  - name: "4"
    display_name: "󰓇"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["Alt+H"]
  - command: "focus right"
    bindings: ["Alt+L"]
  - command: "focus up"
    bindings: ["Alt+K"]
  - command: "focus down"
    bindings: ["Alt+J"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["Alt+Shift+H"]
  - command: "move right"
    bindings: ["Alt+Shift+L"]
  - command: "move up"
    bindings: ["Alt+Shift+K"]
  - command: "move down"
    bindings: ["Alt+Shift+J"]

  # Resize focused window by a percentage or pixel amount.
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "Alt+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "Alt+Ctrl+Space"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+X"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window.
  - command: "close"
    binding: "Alt+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec %USERPROFILE%\\scoop\\apps\\wezterm\\current\\wezterm-gui.exe"
    binding: "Alt+Enter"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "focus workspace 8"
    binding: "Alt+8"
  - command: "focus workspace 9"
    binding: "Alt+9"

  # Move focused workspace to a monitor in a given direction.
  - command: "move workspace left"
    binding: "Alt+A"
  - command: "move workspace right"
    binding: "Alt+F"
  - command: "move workspace up"
    binding: "Alt+D"
  - command: "move workspace down"
    binding: "Alt+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]